### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by da-wad** [equinor/seismic-zfp#12]
seismic-zfp does not currently function on Windows environments, due to lack of support from dependencies. Ideally this should be solved by working on these dependencies to provide Windows support and minimal code changes in this repo, but may require building and packaging C code for ZFP in seismic-zfp.

**Comment by ToreAad** [comment]
I managed to make seismic-zfp run on windows without to much hassle. The only problem is the pyzfp library. Its setup.py calls `make` to build the binaries. I got pyzfp working by commenting out the function that calls `make`, building the zfp library using cmake and visual studio instead, then pointing the the pyzfp setup file to the include and lib files built by visual studio. I also had to add zfp.dll to a folder in path. Building binaries for python on windows is a bit of a pain. It would be nice if pyzfp had a conda package with prebuilt binaries.

**Comment by da-wad** [comment]
Yes - the hassle for me has mainly come from Equinor's restrictions on what I may and may not do on my company Windows laptop. However, with some creative thinking I have achieved a similar end by building the ZFP library's own Python bindings. I expect this will prove a more sustainable route to achieving both Windows & Linux builds/distributions, as it will be possible to get the latest from ZFP without an intermediary package. See the zfpy branch, and I'll keep this issue up to date with progress.

**Comment by da-wad** [comment]
Pre-built binaries for ZFPY can now be installed via pip, using the test PyPI: https://test.pypi.org/project/zfpy/ ... on both Windows and Linux. This means it's now possible to use seismic-zfp on Windows without needing a compiler, although the situation is not totally ideal until ZFPY hits the main Python Package Index - will keep this issue open until then.

**Comment by ToreAad** [comment]
Pre-built windows binaries for zfpy can now also be downloaded from conda-forge: https://anaconda.org/conda-forge/zfpy. It would be nice to setup a conda-forge recipe for seismic-zfp when the pyzfp dependency has been changed to zfpy.

**Comment by da-wad** [comment]
ZFPY is now available as official binary distributions from LLNL via PyPI: https://pypi.org/project/zfpy/ (using the multibuild pattern implemented here: https://github.com/LLNL/zfpy-wheels)

The need for a C compiler is now negated for pip users as well as Conda.
